#deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre  
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name:  POSTGRES_PASSWORD
            value: "123456"   
          - name:   POSTGRES_USER
            value: "junior"
          - name: POSTGRES_DB
            value: "aula1"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports: 
  - port: 5432  
    targetPort: 5432
---    
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: conversao
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: conversao 
  template:
    metadata:
      labels: 
        app: conversao
    spec:
      containers:
      - name: conversao
        image: juniormarques/conversao-temperatura:v3
        env: 
        - name: DB_DATABASE    
          value: "aula1"
        - name: DB_USERNAME  
          value: "junior"
        - name: DB_PASSWORD     
          value: "123456"
        - name: DB_HOST     
          value: "postgre"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: conversao-temperatura
spec:
  selector:
    app: conversao 
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 30000
      
  type: NodePort 


